src/objects/AutomaticAPI__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>authProviderId__c</fullName>
        <label>authProviderId</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>authProviderName__c</fullName>
        <label>authProviderName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>authProviderType__c</fullName>
        <label>authProviderType</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AutomaticAPI</label>
</CustomObject>

src/objects/Trip__c.object
<CustomObject>
    <fields>
        <fullName>Automatic_Id__c</fullName>
        <externalId>true</externalId>
        <label>Automatic Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Distance_Meters__c</fullName>
        <label>Distance (Meters)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Driver__c</fullName>
        <label>Driver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Location_Name__c</fullName>
        <label>End Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time_Zone__c</fullName>
        <label>End Time Zone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MPG__c</fullName>
        <label>MPG (Average)</label>
        <precision>13</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Path__c</fullName>
        <label>Path</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Location_Name__c</fullName>
        <label>Start Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time_Zone__c</fullName>
        <label>Start Time Zone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Trips</relationshipLabel>
        <relationshipName>Trips</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>uri__c</fullName>
        <label>uri</label>
        <type>Url</type>
    </fields>
    <label>Trip</label>
    <nameField>
        <displayFormat>AT{0000}</displayFormat>
        <label>Trip Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Automatic_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Automatic Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AutomaticUtils.cls
public class AutomaticUtils {
    private static AutomaticAPI__c settings = AutomaticAPI__c.getInstance();
    private static String authProviderId   = settings.authProviderId__c;
    private static String authProviderName = settings.authProviderName__c;
    private static String authProviderType = settings.authProviderType__c;

    static String baseUrl = 'https://api.automatic.com/v1';
    
    public static String getResource(String accessToken, String path) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint(baseUrl+path);
        req.setMethod('GET');
        req.setTimeout(60*1000);
        req.setHeader('Authorization', 'token '+accessToken);
    
        Http h = new Http();
        HttpResponse res = h.send(req);
        
        System.debug('getResource - HTTP: '+res);
        
        String resp = res.getBody();
        Integer statusCode = res.getStatusCode();
        if (statusCode == 401 || statusCode == 403) {
            System.debug('Refreshing access token');
            Map<String, String> refreshMap = Auth.AuthToken.refreshAccessToken(authProviderId, 
                                              authProviderName, 
                                              accessToken);
            System.debug(refreshMap);
            accessToken = refreshMap.get('AccessToken');
            if (accessToken != null) {
	            return getResource(accessToken, path);
            } else {
                throw new AutomaticException('Error getting access token: '+refreshMap.get('RefreshError'));
            }
        }
        
        System.debug('getResource - JSON: '+resp);

		return resp;        
    }    
    
    public static Vehicle__c makeVehicle(Map<String, Object> vehicle) {
        return new Vehicle__c(
            Automatic_Id__c = (String)vehicle.get('id'),
            Name = (String)vehicle.get('display_name'),
            Year__c = String.valueOf((Integer)vehicle.get('year')),
            Make__c = (String)vehicle.get('make'),
            Model__c = (String)vehicle.get('model'),
            Color__c = (String)vehicle.get('color')
        );
    }
    
    public static Trip__c makeTrip(User u, Vehicle__c v, Map<String, Object> trip) {
    	Map<String, Object> startLocation = (Map<String, Object>)trip.get('start_location');
    	Map<String, Object> endLocation = (Map<String, Object>)trip.get('end_location');
        
    	return new Trip__c(
            Driver__c = u.id,
            uri__c = (String)trip.get('uri'),
            Automatic_Id__c = (String)trip.get('id'),
            Start_Time__c = Datetime.newInstance((Long)trip.get('start_time')),
            Start_Time_Zone__c = (String)trip.get('start_time_zone'),
            End_Time__c = Datetime.newInstance((Long)trip.get('end_time')),
            End_Time_Zone__c = (String)trip.get('end_time_zone'),
            Path__c = (String)trip.get('path'),
            Vehicle__c = v.id,
            MPG__c = (Double)trip.get('average_mpg'),
            Distance_Meters__c = (Double)trip.get('distance_m'),
            Start_Location_Name__c = (String)startLocation.get('name'),
            Start_Location__Latitude__s = (Double)startLocation.get('lat'),
            Start_Location__Longitude__s = (Double)startLocation.get('lon'),
            End_Location_Name__c = (String)endLocation.get('name'),
            End_Location__Latitude__s = (Double)endLocation.get('lat'),
            End_Location__Longitude__s = (Double)endLocation.get('lon') 
        );
    }
}